### ISSUE TITLE
mi.com

### ISSUE THREAD

**Issue by LamJet** [bazingaterry/SYSUv6-DNS#1]
好像url解析崩了，劳烦查看一下

**Comment by LGA1150** [comment]
是上游DNS的问题，已经修复

**Comment by LamJet** [comment]
好像并没有欸，mi.com还是崩的。mi.com后缀的其他某些网站好像也有些问题，看起来好奇怪，图片都很大

**Comment by LGA1150** [comment]
刚才又看了下，好像是小米官网的国外CDN配置的问题，IPv6下被解析到了 `www.mi.com.edgesuite.net` 。
