### ISSUE TITLE
请问一下什么时候会重新启动服务？

### ISSUE THREAD

**Issue by xiejiangzhao** [bazingaterry/SYSUv6-DNS#14]
过来问一下

**Comment by bazingaterry** [comment]
这学期去实习了，极少时间呆在宿舍，所以设备什么的也没带回来...

既然如此，借这个 issue 问问东校的同学们有没有愿意搭建一个公共 DNS 啊，Unix 系统基本都可以搭建呢！

**Comment by bazingaterry** [comment]
或者我回去的时候尝试运行在我的路由器上，但是这个稳定性估计没有以前的好了。

**Comment by bazingaterry** [comment]
恢复服务了。
