### ISSUE TITLE
无法链接到微软的服务器

### ISSUE THREAD

**Issue by wby238** [bazingaterry/SYSUv6-DNS#15]
在装VS2017时发现的
用这个DNS时无法链接到微软的服务器
改为自动获取后就可以链接到了

**Comment by bazingaterry** [comment]
能具体提供一下是哪个域名吗？不然只能等 @LGA1150 有空的时候解决了。

**Comment by LGA1150** [comment]
download.microsoft.com IPv4 的问题
@bazingaterry IP 换为 180.88.62.125

**Comment by bazingaterry** [comment]
@LGA1150 

`curl https://download.microsoft.com -I -4` 提示 Invalid certificate chain

**Comment by LGA1150** [comment]
@bazingaterry 我测试正常啊，你是不是得更新下 ca-certificates?
