### ISSUE TITLE
请问今天宕机了么？

### ISSUE THREAD

**Issue by panyang970422** [bazingaterry/SYSUv6-DNS#16]
如题

**Comment by charlieleex** [comment]
看起来是的，建议在本地搭一个dns，这里推荐dnsagent，不同地址给不同的dns解析，这样即使这里崩了，国内的网站基本没事

**Comment by bazingaterry** [comment]
@panyang970422 @charlieleex 也许是的，因为我在外实习的关系，已经好几天没回宿舍了。我宿舍的路由器的偶尔会宕机，所以也希望有同学能负责提供更好的部署环境。

**Comment by LiuZHolmes** [comment]
@bazingaterry 尝试搭建了本地的dns服务器，用Pcap_DNSProxy做的。请问config文件要具体怎么改呢？我把你的Pcap_DNSProxy文件放进Pcap_DNSProxy的目录下，并改了它原本的config.ini中的Hosts File Name和IPFilter File Name（添加了你的.conf文件）。目前能上reddit，ins。也能nslookup到google的地址，但是ping不通也不能打开google，你的dns服务器宕机前我是可以上的。是不是我搭建哪里出了问题呢？（我是SYSU校园网）

**Comment by bazingaterry** [comment]
Pcap_DNSProxy 的文件夹可以直接替换掉自带配置的文件夹，然后 conf 里面的文件是 dnsmasq 的，配置默认是将 Pcap_DNSProxy 作为 dnsmasq 的上游。

**Comment by LiuZHolmes** [comment]
所以我只需要替换掉配置文件就可以了吗？

**Comment by bazingaterry** [comment]
@LiuZHolmes 不用 dnsmasq 有些加速会不生效，有没有启动成功你看看有没有后台的进程和 Log 文件。

**Comment by LiuZHolmes** [comment]
应该是成功了，我现在能上一些网站。但谷歌还是不行，应该是这个问题。但是win10没法用dnsmasq…

**Comment by bazingaterry** [comment]
@LiuZHolmes 可以试试 docker 之类的东西运行 dnsmasq

**Comment by panyang970422** [comment]
@bazingaterry 用树莓派来搭建DNS会不会有性能问题？

**Comment by LiuZHolmes** [comment]
@bazingaterry 好的谢谢!(突然有能上google了...

**Comment by bazingaterry** [comment]
@panyang970422 小规模使用不会
