### ISSUE TITLE
请问能给出一个详细的搭建教程吗？

### ISSUE THREAD

**Issue by wby238** [bazingaterry/SYSUv6-DNS#21]
好像现在已经不能用了，想尝试一下自己搭建，然而却被那两个工具劝退了……

**Comment by bazingaterry** [comment]
具体是什么系统环境呢？在 macOS 或者 Linux 下面搭建应该都很简单。

**Comment by wby238** [comment]
linux下就行了，可以拿树莓派来试一下。

**Comment by bazingaterry** [comment]
[dnsmasq](https://wiki.debian.org/HowTo/dnsmasq)
[Pcap_DNSProxy](https://github.com/chengr28/Pcap_DNSProxy/blob/master/Documents/ReadMe_Linux.zh-Hans.txt)

@wby238 给你两份文档供参考。

**Comment by wby238** [comment]
我在win7下只使用了Pcap_DNSProxy来搭建一个本地DNS服务器，极路由的IPv6选项里选了DHCPv6，最后本地连接的IPv6一会能用，一会无Internet链接，一般我都是靠停止本地连接后再启动来使得IPv6能用，这是出了什么问题？

**Comment by LGA1150** [comment]
极路由这个 DHCPv6 插件是通过 NAT64 实现的，不太稳定。建议取得 root 权限后用 radvd + ndppd 实现路由器后获得公网 IPv6。也可以尝试第三方固件。

**Comment by LGA1150** [comment]
既然你有树莓派，你就可以直接在树莓派上装 LEDE 和 [H3C 客户端](https://github.com/Testla/h3c) 这个是我目前在 R6300v2 用的，纯 C 编写，支持断线重拨。

**Comment by wby238** [comment]
thx
还有就是在访问某些地址时会将这些地址全部解析为218.199.110.70，导致网页的js等资源加载失败，这是什么原因呢？

目前出现过的解析失败的网址有：b站的静态资源地址*.hdslb.com，实验楼的静态资源地址*.shiyanlou.com

目前的解决方法是手动找出对应网址的ip然后添加到hosts中

**Comment by LGA1150** [comment]
@wby238 
你用了很久之前的配置？

**Comment by wby238** [comment]
是5月的版本，最新的还没pull
不过Windows版本的配置跟这里提供的会有差别，直接覆盖的话会出错……

**Comment by LGA1150** [comment]
最新的与你目前用的有很大区别

**Comment by wby238** [comment]
刚刚试着更换一下配置，发现只要删除第124行就能在windows上使用了。
```
HTTP CONNECT Header Field = Content-Length: 0
```

**Comment by wby238** [comment]
现在用着最新的，还是有些网址无法解析，例如docker store的图片用的AWS服务器：
```
d1q6f0aelx0por.cloudfront.net
```
在VPS上ping出的ip是52.84.203.113，本机无法解析出ip
