### ISSUE TITLE
老哥能否实现到LOL西欧服的一个加速

### ISSUE THREAD

**Issue by ZM-J** [bazingaterry/SYSUv6-DNS#25]
![吃翔的ping](https://user-images.githubusercontent.com/21689514/33802466-ddeb1656-ddb2-11e7-819b-f616bca23d2a.png)
)

可以看到上面ping非常吃翔
能否实现到西欧服的加速？想和朋友开开黑，，，，，

**Comment by LGA1150** [comment]
首先你要知道 DNS 的作用。
本项目是将一些国内外网站的域名解析至校内访问快的 CDN 实现的，游戏服务器这些单 IP 的没办法加速。请自备加速器或代理。
