### ISSUE TITLE
能否弄一个到overleaf的加速

### ISSUE THREAD

**Issue by ZM-J** [bazingaterry/SYSUv6-DNS#26]
虽然不想过多麻烦老哥，99%的几率又被ignore掉，但是想了想还是发此issue
现在改了DNS之后，到 [overleaf](https://www.overleaf.com) 点create a paper，然后加载不出来。
老哥有办法解决不QAQ

**Comment by LGA1150** [comment]
无法复现问题，你可以打开开发者工具查看是哪个请求失败了
