### ISSUE TITLE
学校是不是开启了IPv6的防火墙，不能开服务器传文件了

### ISSUE THREAD

**Issue by FanFansfan** [bazingaterry/SYSUv6-DNS#28]
以前试过用python跑个http脚本给外校同学传文件，现在不能用了，接口完全收不到传入连接的数据包。
在华农的同学电脑上实验了，他们能够架设服务器，甚至80,8080端口也是开放的。
@LamJet

**Comment by LGA1150** [comment]
是的，目前只有ICMPv6能通

**Comment by etnperlong** [comment]
是的，全部端口都被Filter了
