### ISSUE TITLE
IPv6 桥接路由器自身无法获取IPv6地址

### ISSUE THREAD

**Issue by LiJinyao** [bazingaterry/SYSUv6-DNS#35]
感谢教程，按照[如何在路由器后获取 IPv6 地址
WiKi](https://github.com/bazingaterry/SYSUv6-DNS/wiki/%E5%A6%82%E4%BD%95%E5%9C%A8%E8%B7%AF%E7%94%B1%E5%99%A8%E5%90%8E%E8%8E%B7%E5%8F%96-IPv6-%E5%9C%B0%E5%9D%80)中桥接方法让 LAN 内的设备获取到了 IPv6 地址。但是按照让路由器本身获取IPv6的方法无法让路由器获取IPv6，有什么 Debug 的方法吗？
我的 LAN 口通过 `nvram get lan_ifname` 获得，是 `br0` 
根据 WiKi 设置：
```
echo 0 > /proc/sys/net/ipv6/conf/br0/disable_ipv6
echo 2 > /proc/sys/net/ipv6/conf/br0/accept_ra
ip6tables -F
ip6tables -X
ip6tables -P INPUT ACCEPT
ip6tables -P OUTPUT ACCEPT
```
设置后 `br0` 只有一个本地 IPv6 地址，没有获取到 IPv6。
```
br0       Link encap:Ethernet  HWaddr 0C:9D:92:4A:D5:30
          inet addr:192.168.50.1  Bcast:192.168.50.255  Mask:255.255.255.0
          inet6 addr: fe80::e9d:92ff:fe4a:d530/64 Scope:Link
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:159183 errors:0 dropped:8 overruns:0 frame:0
          TX packets:130683 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:39984422 (38.1 MiB)  TX bytes:15629824 (14.9 MiB)
```
我所处的网络环境是通过 DHCPv6 下发一个 128 前缀的 IPv6 地址，会跟这个有关吗？

**Comment by aur3l14no** [comment]
请问你后来是如何解决这个问题的呢

**Comment by LiJinyao** [comment]
我在张大妈上发了解决方法。https://post.smzdm.com/p/alpz5z98/?send_by=6898997913
