### ISSUE TITLE
TG邀请链接过期

### ISSUE THREAD

**Issue by flyingmanPan** [bazingaterry/SYSUv6-DNS#36]
如题

**Comment by kamingchan** [comment]
![image](https://user-images.githubusercontent.com/9930758/56291083-24dca600-6157-11e9-84c7-79b7f421c0e0.png)

似乎並沒有。

**Comment by flyingmanPan** [comment]
![image](https://user-images.githubusercontent.com/9375024/56291188-5f464300-6157-11e9-8d6d-f52903d810bf.png)
突然退群,是被ban了?
