### ISSUE TITLE
请问是公共dns是在维护吗？

### ISSUE THREAD

**Issue by LamJet** [bazingaterry/SYSUv6-DNS#6]
google搜索页面能打开，二级页面全都崩了好像，github都打不开好像。。。

**Comment by bazingaterry** [comment]
是的，新版的 Pcap_DNSProxy 在新的服务器上一直崩溃，我在想办法。

有什么新进展我会在这里及时更新。

**Comment by bazingaterry** [comment]
已经退回 2.5 版本，等待该 [issue](https://github.com/chengr28/Pcap_DNSProxy/issues/161) 有进展再更新。
