### ISSUE TITLE
这是巧合吗？

### ISSUE THREAD

**Issue by LGA1150** [bazingaterry/SYSUv6-DNS#9]
优酷土豆的教育网节点 `58.205.218.0/24` `118.228.16.0/24` 在校内疑似被屏蔽，traceroute最后一跳为学校长城宽带出口地址

<html><head><title>优酷</title></head><body bgcolor="white">

<center><h2>WinMTR statistics</h2></center>

<p align="center"> <table border="1" align="center">

<tr><td>Host</td> <td>%</td> <td>Sent</td> <td>Recv</td> <td>Best</td> <td>Avrg</td> <td>Wrst</td> <td>Last</td></tr>

<tr><td>192.168.199.1</td> <td>   0</td> <td>   5</td> <td>   5</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   1</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>10.44.97.201</td> <td>   0</td> <td>   5</td> <td>   5</td> <td>   1</td> <td>   1</td> <td>   1</td> <td>   1</td></tr>

<tr><td>10.44.34.201</td> <td>   0</td> <td>   5</td> <td>   5</td> <td>   0</td> <td>   1</td> <td>   5</td> <td>   5</td></tr>

<tr><td>10.44.16.201</td> <td>  20</td> <td>   5</td> <td>   4</td> <td>   1</td> <td>   1</td> <td>   1</td> <td>   1</td></tr>

<tr><td>220.115.185.89</td> <td>   0</td> <td>   5</td> <td>   5</td> <td>   2</td> <td>   2</td> <td>   3</td> <td>   2</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

</table></body></html>

<html><head><title>土豆</title></head><body bgcolor="white">

<center><h2>WinMTR statistics</h2></center>

<p align="center"> <table border="1" align="center">

<tr><td>Host</td> <td>%</td> <td>Sent</td> <td>Recv</td> <td>Best</td> <td>Avrg</td> <td>Wrst</td> <td>Last</td></tr>

<tr><td>192.168.199.1</td> <td>   0</td> <td>   4</td> <td>   4</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   1</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>10.44.97.201</td> <td>   0</td> <td>   4</td> <td>   4</td> <td>   1</td> <td>   2</td> <td>   7</td> <td>   1</td></tr>

<tr><td>10.44.34.201</td> <td>   0</td> <td>   4</td> <td>   4</td> <td>   0</td> <td>   0</td> <td>   1</td> <td>   0</td></tr>

<tr><td>10.44.16.201</td> <td>  25</td> <td>   4</td> <td>   3</td> <td>   1</td> <td>   1</td> <td>   1</td> <td>   1</td></tr>

<tr><td>220.115.185.89</td> <td>   0</td> <td>   4</td> <td>   4</td> <td>   2</td> <td>   2</td> <td>   2</td> <td>   2</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

<tr><td>Request timed out.</td> <td> 100</td> <td>   1</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>

</table></body></html>

EDIT: 如果是有网络中心的人觉得这两段IP挤占教育网IPv4带宽，你可以在这里提issue投诉，也可以适当限速， **但请不要干这种偷偷完全屏蔽的一刀切懒政!**

**Comment by LGA1150** [comment]
helpdesk@mail.sysu.edu.cn 
这个是帮助台邮箱，可以把问题发过去
例：`http://edu-k.youku.com/crossdomain.xml 打不开`
另外，以下IP段应该经过长宽出口，实际上却没有：
```
58.66.0.0/15
124.172.0.0/15
124.193.0.0/16
115.182.0.0/20
```

**Comment by LamJet** [comment]
我们老师说10.8这两个dns的话和一些下载是走长城带宽加速出口的。但不知道你的问题是不是这个
哈哈，看到你comment。。。

**Comment by LGA1150** [comment]
@LamJet 
学校默认的DNS根本没有作什么特殊处理，纯粹是转发和缓存运营商（移动、联通）的DNS

**Comment by LamJet** [comment]
虽然学校的dns确实很渣吧，但加速出口是有的好像。。。（我有理解错么？还是说连加速出口都是运营商的？

**Comment by LGA1150** [comment]
@LamJet 
所谓加速是通过设置静态路由实现的，在不按域名分区解析的情况下，效果 **十分有限**

**Comment by LamJet** [comment]
额，我还是说明一下，虽然我是网络中心的，但我并没有权限了解到学校对于ip屏蔽的事情。我只是尽我能力把能了解到的可以告诉你，但是我还是一个小白，不太懂这些事。。。

**Comment by LamJet** [comment]
@LGA1150 
分区是指分地区么？之前只知道老师说优酷好像出了点问题，恰好看到这个评论，就问了一下老师，老师说现在已经算弄好了。。。。。。但至于为什么会屏蔽教育网，（能贴图么？）老师是说可能教育网还有缺陷什么的。最好还是发邮件到南校吧，或者我也可以帮你们下单，在不违反纪律的前提下，我可以帮你们关注后续。。。

**Comment by LGA1150** [comment]
@LamJet 
配置静态路由的操作十分简单，我还在Windows下配置过；

“教育网还有缺陷”这是把锅强行甩给教育网了，这两段IP之前就正常地走教育网出口，速度20Mbps，现在出现这种情况显然是人为的

**Comment by LamJet** [comment]
@LGA1150 那还是下单问南校的人吧。如果只是东校的问题我在跟这边的老师说，不过工单的话应该都是会得到回复的

**Comment by LGA1150** [comment]
@LamJet 
针对教育网和长宽的静态路由在所有校区都一样

**Comment by LamJet** [comment]
额，我的意思是因为其实差不多所有事情都是归南校管的，东校能干的还是很少。发帮助台邮箱也是南校处理的，所以我的本来的意思就是发帮助台邮箱质问一下他们吧。（嗯，我在这里也是跳到长城带宽

**Comment by LamJet** [comment]
@LGA1150
好像现在校园网连优酷的网页都无法打开了，追踪路径的时候，优酷的教育网节点好像又多了一跳，跳到本地的交换机去了？不知道这是什么问题。。。。

**Comment by bazingaterry** [comment]
几天前给帮助台发了邮件，打电话来确认之后就没了下文。

**Comment by LamJet** [comment]
请问下那个工作单号是什么？我看下

2016-09-27 15:44 GMT+08:00 bazingaterry <notifications@github.com>:

**Comment by LGA1150** [comment]
117.121.54.225 
ark.letv.com
一样的情况
